title: Example of Jekyll website
email: nrsalinas@gmail.com
description: Test website with Slate Jekyll theme.
show_downloads: false
google_analytics:
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nrsalinas.github.io/website_simple/ # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
twitter_username: mytwetter
github_username:  nrsalinas

# Build settings
#remote_theme: pages-themes/slate@v0.2.0
theme: jekyll-theme-slate
#plugins:
#  - jekyll-feed
#  - jekyll-remote-theme
