title: Example of Jekyll website
email: nrsalinas@gmail.com
description: Test website with Slate Jekyll theme.
show_downloads: false
google_analytics:
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://nrsalinas.github.io/website_simple/ # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
twitter_username: mytwetter
github_username:  nrsalinas

# Build settings
#theme: jekyll-theme-slate # if building locally
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
